name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  static-code-analysis:
    name: "Static Code Analysis"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        laravel-version:
          - "^6"
          - "^7"
          - "^8"
        exclude:
          - php-version: "7.2"
            laravel-version: "^8"
          - php-version: "8.0"
            laravel-version: "^6"
          - php-version: "8.0"
            laravel-version: "^7"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: "Install dependencies with composer"
        run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-interaction

      - name: "Run phpstan/phpstan"
        run: vendor/bin/phpstan analyse
